# https://stackoverflow.com/questions/59813998/github-actions-splitting-workflow-file

name: pnpm-action
runs:
  using: composite
  steps:
    - name: Use Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Setup PNPM
      uses: pnpm/action-setup@v2
      with:
        version: 7
        run_install: false

    - name: Get PNPM directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Use cached pnpm
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
