import Head from 'next/head'
import Image from 'next/image'
import { Button, Container } from '@elementail/core'

export default function Home() {
    return (
        <Container className='flex min-h-screen flex-col items-center justify-center py-2'>
            <Head>
                <title>Elementail Demo Next.js</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <h1>
                    Welcome to <a href='https://nextjs.org'>Next.js!</a>
                </h1>

                <p>
                    Get started by editing <code>pages/index.tsx</code>
                    <Button variant='primary'>Sample Button</Button>
                </p>

                <div>
                    <a href='https://nextjs.org/docs'>
                        <h2>Documentation &rarr;</h2>
                        <p>Find in-depth information about Next.js features and API.</p>
                    </a>

                    <a href='https://nextjs.org/learn'>
                        <h2>Learn &rarr;</h2>
                        <p>Learn about Next.js in an interactive course with quizzes!</p>
                    </a>

                    <a href='https://github.com/vercel/next.js/tree/canary/examples'>
                        <h2>Examples &rarr;</h2>
                        <p>Discover and deploy boilerplate example Next.js projects.</p>
                    </a>

                    <a
                        href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
                        target='_blank'
                        rel='noopener noreferrer'
                    >
                        <h2>Deploy &rarr;</h2>
                        <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
                    </a>
                </div>
            </main>

            <footer>
                <a
                    href='https://vercel.com?utm_source=elementail.js.org&utm_medium=website&utm_campaign=elementail'
                    target='_blank'
                    rel='noopener noreferrer'
                >
                    Powered by{' '}
                    <span>
                        <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
                    </span>
                </a>
            </footer>
        </Container>
    )
}
