name: CI

on:
  push:
    branches: [main]

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-website:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get PNPM directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Use cached pnpm
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        name: Deps install and build
        run: |
          pnpm install --frozen-lockfile
          pnpm run export

      - name: Configuring Github Pages
        run: |
          touch ./apps/website/out/.nojekyll
          touch ./apps/website/out/CNAME
          echo 'elementail.js.org' > ./apps/website/out/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} # This option defaults to the repository scoped GitHub Token.
          repository-name: riipandi/elementail # Specify the github repository path.
          branch: gh-pages # The branch the action should deploy to.
          folder: apps/website/out # The folder the action should deploy.
