name: CI

on:
  push:
    branches: [main]

jobs:
  build-website:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Run PNPM action
        uses: ./.github/pnpm-action

      - if: ${{ steps.cache-pnpm.outputs.cache-hit != 'true' }}
        name: Deps install and build
        run: |
          pnpm install
          pnpm export

      - name: Configuring Github Pages
        run: |
          touch ./apps/website/out/.nojekyll
          touch ./apps/website/out/CNAME
          echo 'elementail.js.org' > ./apps/website/out/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          token: ${{ secrets.DEPLOY_TOKEN }} # This option defaults to the repository scoped GitHub Token.
          repository-name: riipandi/elementail # Specify the github repository path.
          branch: gh-pages # The branch the action should deploy to.
          folder: apps/website/out # The folder the action should deploy.
