name: Build and Release

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PNPM Package Manager
        uses: pnpm/action-setup@v2
        with:
          version: ^7.17
          run_install: |
            - args: [--global, prettier, tailwindcss]
            - args: [--no-frozen-lockfile]

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Send a Slack notification if a publish happens
      #   if: steps.changesets.outputs.published == 'true'
      #   # You can do something when a publish happens.
      #   run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"

  build-website:
    needs: [release-packages]
    timeout-minutes: 15
    runs-on: ubuntu-latest

    # https://turbo.build/repo/docs/ci/github-actions
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup PNPM Package Manager
        uses: pnpm/action-setup@v2
        with:
          version: ^7.17
          run_install: |
            - args: [--global, prettier, tailwindcss]
            - args: [--no-frozen-lockfile]

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          retention-days: 1
          cache: 'pnpm'

      - name: Persist Next.js build cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/apps/website/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('pnpm-lock.yaml') }}-

      - name: Install dependencies
        run: pnpm install

      - name: Build static website
        run: |
          pnpm build
          pnpm export

      - name: Save Next.js artifact
        uses: actions/upload-artifact@v3
        with:
          name: website-artifact ${{ matrix.node-version }}
          path: apps/website/.next
          if-no-files-found: error
          retention-days: 1

      - name: Configure Github Pages
        run: |
          touch ./apps/website/out/{.nojekyll,CNAME}
          echo 'elementail.js.org' > ./apps/website/out/CNAME
          mv ./apps/docs/storybook-static ./apps/website/out/storybook

      - name: Deploy website 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # ssh-key: ${{ secrets.DEPLOY_KEY }} # ssh-keygen -t rsa -m pem -b 4096 -C "aris@duck.com" -N ""
          token: ${{ secrets.GH_TOKEN }} # This option defaults to the repository scoped GitHub Token.
          repository-name: riipandi/elementail # Specify the github repository path.
          branch: gh-pages # The branch the action should deploy to.
          folder: apps/website/out # The folder the action should deploy.
          silent: true

      - name: Deploy Storybook 🚀
        uses: chromaui/action@v1
        env:
          CHROMATIC_RETRIES: 2
          LOG_LEVEL: 'error'
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GH_TOKEN }}
          workingDir: apps/docs
          # storybookBuildDir:
